export const GAMES_ALL_REQUEST = 'GAMES_ALL_REQUEST';
export const GAMES_ALL_SUCCESS = 'GAMES_ALL_SUCCESS';
export const GAMES_ALL_FAIL = 'GAMES_ALL_FAIL';

export const GAMES_CATEGORY_REQUEST = 'GAMES_CATEGORY_REQUEST';
export const GAMES_CATEGORY_SUCCESS = 'GAMES_CATEGORY_SUCCESS';
export const GAMES_CATEGORY_FAIL = 'GAMES_CATEGORY_FAIL';

export const ONE_GAME_REQUEST = 'ONE_GAME_REQUEST';
export const ONE_GAME_SUCCESS = 'ONE_GAME_SUCCESS';
export const ONE_GAME_FAIL = 'ONE_GAME_FAIL';